### ISSUE TITLE
Some styles are not applied in production mode with "srcDir" nuxt.config.js option.

### ISSUE THREAD

**Issue by peterkimzz** [nuxt-community/tailwindcss-module#114] opened 2020-05-25 12:32 UTC
### Version
@nuxtjs/tailwindcss: 2.0.0
nuxt: 2.12.0

### What is actually happening?

Hi, this is Peter.

I tried to install this module, worked perfectly in dev mode, but some tailwind css has not been applied when I executed `nuxt build` and `nuxt start`.

**Without "srcDir" option in production mode**

![image](https://user-images.githubusercontent.com/20244536/82812739-9fd1cd80-9ece-11ea-88a2-046a73ecf31d.png)
![image](https://user-images.githubusercontent.com/20244536/82812756-a8c29f00-9ece-11ea-8a65-205c5dffc9c6.png)

As you can see, tailwind's class styles `.bg-black` and `.container` are applied.

**With "srcDir" options in production mode**

![image](https://user-images.githubusercontent.com/20244536/82812611-541f2400-9ece-11ea-8159-b18c553748b4.png)
![image](https://user-images.githubusercontent.com/20244536/82812628-600ae600-9ece-11ea-8b72-674dc7c1dea3.png)

The problem is that `.container` style is applied, `.bg-black` is not applied with all scripts are in `srcDir`.

I tried to install all dependencies by using both `npm` and `yarn`, but got same result.

Please let me know If my configuration is wrong! Thank you.

----

[10, August]
**@nuxtjs/tailwindcss** has been updated from 2.x to 3.0, still got same issue.

**Comment by nielsdB97** [comment] 2020-05-28 15:52
@peterkimzz I am currently running into the same problem.

I found that the problem is caused by PurgeCSS, which is a tool that strips all unused CSS from your application build. This way whatever Tailwind utitilies you don't use are also not shipped to the user, resulting in smaller payloads and thereby better performance.

In my project I write my pages and components in `.vue` files. For the `<style>` blocks with `@apply` directives everything seems to work just fine. However the classes used directly in the `<template>` tag are somehow not found and therefore purged.

PurgeCSS is only enabled in production mode, which is why your development environment works just fine but the output of both the `build` and `generate` scripts don't.

**Comment by misikoff** [comment] 2020-06-30 19:04
It appears as if the same issue occurs when the nuxt.config.js is in a subdirectory of the package.json and the rootDir is specified via an argument for the nuxt command, as described in example 2 on this page: https://nuxtjs.org/api/configuration-srcdir/

As @nielsdB97 experienced, the <style> blocks with @apply directives seem to work, but the classes used directly in the <template> tag are not found and therefore purged.

**Comment by husarcik** [comment] 2020-08-09 16:51
I'm having a similar issue. If I convert the relative paths to absolute paths it works no problem. I've noticed a few other modules do a conversion using srcDir before passing to purgeCSS. A good example of that is the nuxt-bulma-slim. Is this something we should be doing for this module too? See link for an example.

https://github.com/mustardamus/nuxt-bulma-slim/blob/b31a1ee3a60c016106bbaf1595d1c3674cb1efc4/lib/get-options.js

**Comment by nielsdB97** [comment] 2020-08-14 15:13
To demonstrate the problem I have created [a demo repository](https://github.com/nielsdB97/nuxt-tailwind-purge-demo/tree/src-dir). The master branch is a nearly default nuxt init, whereas the linked `src-dir` branch has all contents moved into a `src` folder.

When running `yarn dev` it will work fine since it's not doing any purging.
However when doing a production build by running `yarn generate` followed by `yarn start`, the inline styles don't work as intended:

- The text "Should be hidden" in the "Documentation" button should not be visible
- The text "Documentation" should be in the color red

I hope this will be helpful in resolving the issue. Thanks in advance!

**Comment by nielsdB97** [comment] 2020-08-18 10:12
Until this issue will get resolved I found this temporary workaround based on @husarcik his comment:

**tailwind.config.js**
```js
import nuxtConfig from "./nuxt.config";

export default {
  purge: {
    content(defaultContents) {
      return defaultContents
        .map((path) => join(nuxtConfig.srcDir, path))
        .map((file) => file.replace(".js", ".ts"));
    }
  }
}
```

**Comment by Atinux** [comment] 2020-09-14 15:16
Hi, can you confirm this bug with the version 3 of this module?

**Comment by misikoff** [comment] 2020-09-14 20:18
I can confirm this issue still occurs. I just pulled down https://github.com/nielsdB97/nuxt-tailwind-purge-demo/tree/src-dir and replicated the problem with version 3 of the module.

**Closed** 2020-09-25 11:42 UTC
Labels: bug

**Comment by Atinux** [comment] 2020-09-25 11:50
Hi @misikoff 

First, you need to move `tailwind.config.js` in the `src/` directory **OR** to define `configPath: '~~/tailwind.config.js'` (`~~` is the alias for `rootDir`, see https://nuxtjs.org/guides/directory-structure/assets#aliases).

Then you will see a message saying:

```bash
Merging Tailwind config from ~/tailwind.config.js
```

I actually merged #170 and released the [v3.1.0](https://github.com/nuxt-community/tailwindcss-module/releases/tag/v3.1.0) supporting the `srcDir` as well as TypeScript, so you can update your dependency and it's good to go 🚀

**Comment by aaronhuisinga** [comment] 2020-09-25 18:43
@Atinux It seems to me that when using the new config file format (passing in parameters and returning a function), Tailwind isn't properly reading the config at all. When migrating our existing config to the new format (and updating to v3.1.0), none of our config options are applied. If I revert it back to the old format (still on v3.1.0), everything works correctly.

**Comment by Atinux** [comment] 2020-09-30 09:40
@aaronhuisinga this is another issue, please create one with a reproduction please.
