### ISSUE TITLE
5.0.0-4 and Nuxt Bridge: `The requested module '@nuxt/kit' does not provide an export named 'createResolver'`

### ISSUE THREAD

**Issue by madebyfabian** [nuxt-community/tailwindcss-module#432] opened 2022-02-18 14:27 UTC
### Version
@nuxtjs/tailwindcss: `5.0.0-4`
nuxt-edge: `2.16.0-27358576.777a4b7f`
@nuxt/bridge: `npm:@nuxt/bridge-edge@^3.0.0-27374259.21b664c`

### Reproduction Link
https://github.com/madebyfabian/nuxt-bridge-tailwind-module-5-issue-reprod

### Steps to reproduce
- Start Dev Server on the Reprod Repo

### What is Expected?
Dev Server Working, Builds Working, No Errors

### What is actually happening?
Hello there! I have an issue with the newest version of this package (5). After installing the package like in the Setup tutorial, I get this message when I try to build or start the dev server.
Dev Server erroring:
```bash
 FATAL  The requested module '@nuxt/kit' does not provide an export named 'createResolver'

import { defineNuxtModule, resolvePath, resolveAlias, createResolver, requireModule, addTemplate, isNuxt2, installModule, addServerMiddleware } from '@nuxt/kit';
  ^^^^^^^^^^^^^^
  SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'createResolver'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
  at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
  at async ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:174:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:346:5)
```

please check the Reprod Repo on how the project is set up. It's basically a starter nuxt project with Bridge installed.

**Comment by pi0** [comment] 2022-02-18 16:48
(or `npx nuxi upgrade --force` if not explicitly installed kit)

**Comment by pi0** [comment] 2022-02-18 16:52
@madebyfabian Would you please use `nuxi` upgrade command instead? (and if not directly using kit, can remove it from depenednecies)

**Comment by madebyfabian** [comment] 2022-02-18 16:52
@pi0 
I tried it, but the command doesn't even run:
```bash
ERROR  Cannot find module 'nuxt3/package.json'
Require stack:
- /Users/fabian/Desktop/code/_test-nuxt-bridge-minimal

  Require stack:
  - /Users/fabian/Desktop/code/_test-nuxt-bridge-minimal
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at resolveModule (node_modules/nuxi/dist/chunks/cjs.mjs:19:29)
  at getNuxtVersion (node_modules/nuxi/dist/chunks/upgrade.mjs:18:19)
  at Object.invoke (node_modules/nuxi/dist/chunks/upgrade.mjs:40:34)
  at _main (node_modules/nuxi/dist/chunks/index.mjs:384:17)
```

**Comment by pi0** [comment] 2022-02-18 16:53
Then remove and create lock file (yarn.lock or package.lock.json) should have same effect (will check other issue)

**Comment by madebyfabian** [comment] 2022-02-18 17:07
@pi0 If I do this, I get an issue which I get often in nuxt3 and nuxt bridge. From my experience it has something to do if you misconfigure something in nuxt.config. But that's not the case since there is not much configured here. There is an issue open for this in nuxt/framework#3147. 

First of all, the build time is now about 1 minute instead of a few ms, and is stuck at one specific point this minute.
<img width="466" alt="Bildschirmfoto 2022-02-18 um 17 58 34" src="https://user-images.githubusercontent.com/32813692/154728531-7b1dbec6-ba15-44d6-9342-cf16bc3106b5.png">

and after this, the build just keeps refreshing itsself infinitely:
<img width="481" alt="Bildschirmfoto 2022-02-18 um 18 00 36" src="https://user-images.githubusercontent.com/32813692/154728565-ad562463-cb1b-4eb0-a5cf-f6cf34ec840e.png">

So any of the upgrades that happen while removing `package-lock.json` and re-installing it breaks nuxt. I've added the failing new `package-lock.json` to a branch of my reprod repo: https://github.com/madebyfabian/nuxt-bridge-tailwind-module-5-issue-reprod/tree/failing--upgraded-package-lock.json

**Comment by DouglasCalora** [comment] 2022-03-18 02:44
I'm getting the same issue! nuxt has a lot of problems

**Comment by DouglasCalora** [comment] 2022-03-18 02:45
@madebyfabian did you fixed it?

**Comment by madebyfabian** [comment] 2022-03-18 07:14
@DouglasCalora haven‘t managed to find a fix for it, moved away from wanting to use nuxt3/bridge in prod.

**Comment by danielroe** [comment] 2022-03-18 09:24
You're right, at the moment we're not able to pin requirements to a specific version because we're using edge releases. However, the cause of this is that you are using an older version of kit (likely because of your version of bridge, which is two months old, and this feature only landed a month ago).

We can definitely improve the `nuxi upgrade` experience for bridge (currently it's not supported).

For now, and for reference, to upgrade your nuxt bridge version, run:

```bash
npm up @nuxt/bridge
npm up @nuxtjs/tailwindcss
```

I'm going to close the issue in favour of https://github.com/nuxt/framework/issues/3764. Rest assured we want to make this feel better. ❤️

**Closed by danielroe** 2022-03-18 09:24 UTC
Labels: bug

**Comment by DouglasCalora** [comment] 2022-03-18 13:11
@madebyfabian i'm using nuxt v2 and get this issue

**Comment by kon3ko** [comment] 2022-04-15 14:11
> 

remove node_modules, yarn.lock
install all packages again and run dev
