### ISSUE TITLE
Nuxt3 Tailwind Viewer don't work

### ISSUE THREAD

**Issue by ilovesusu** [nuxt-community/tailwindcss-module#459] opened 2022-04-19 15:13 UTC
nuxt3  use "@nuxtjs/tailwindcss": "^5.0.2"   

Tailwind Viewer don't work

Canvas.vue:120          GET http://localhost:3000/_tailwind/config.json 404 (Not Found)

**Comment by florian-lefebvre** [comment] 2022-04-19 18:06
I'm facing the same issue

**Comment by Atinux** [comment] 2022-04-20 22:09
It works on my end, do you have a reproduction?

**Comment by asen23** [comment] 2022-04-21 15:35
> It works on my end, do you have a reproduction?

https://codesandbox.io/s/smoosh-moon-oloppv
Navigate to https://oloppv.sse.codesandbox.io/_tailwind/
See network tab
![image](https://user-images.githubusercontent.com/31660481/164497461-d45a5033-31f8-41e4-a880-5bb7a31a04cc.png)

**Comment by BulgarianHealer** [comment] 2022-04-22 12:41
On fresh install

`[Vue Router warn]: No match found for location with path "/_tailwind/"
[Vue Router warn]: No match found for location with path "/_tailwind/"
[Vue Router warn]: No match found for location with path "/_tailwind/"
[Vue Router warn]: No match found for location with path "/_tailwind/"
[Vue Router warn]: No match found for location with path "/_tailwind/css/app.aac7915f.css"
[Vue Router warn]: No match found for location with path "/_tailwind/css/app.aac7915f.css"
[Vue Router warn]: No match found for location with path "/_tailwind/css/app.aac7915f.css"
[Vue Router warn]: No match found for location with path "/_tailwind/css/app.aac7915f.css"
[Vue Router warn]: No match found for location with path "/_tailwind/js/app.eb7ca967.js"
[Vue Router warn]: No match found for location with path "/_tailwind/js/app.eb7ca967.js"
[Vue Router warn]: No match found for location with path "/_tailwind/js/app.eb7ca967.js"
[Vue Router warn]: No match found for location with path "/_tailwind/js/app.eb7ca967.js"
[Vue Router warn]: No match found for location with path "/_tailwind/js/chunk-vendors.d4b2e20c.js"
[Vue Router warn]: No match found for location with path "/_tailwind/js/chunk-vendors.d4b2e20c.js"
[Vue Router warn]: No match found for location with path "/_tailwind/js/chunk-vendors.d4b2e20c.js"
[Vue Router warn]: No match found for location with path "/_tailwind/js/chunk-vendors.d4b2e20c.js"
[Vue Router warn]: No match found for location with path "/_tailwind/js/chunk-vendors.d4b2e20c.js.map"
[Vue Router warn]: No match found for location with path "/_tailwind/js/chunk-vendors.d4b2e20c.js.map"
[Vue Router warn]: No match found for location with path "/_tailwind/js/chunk-vendors.d4b2e20c.js.map"
[Vue Router warn]: No match found for location with path "/_tailwind/js/chunk-vendors.d4b2e20c.js.map"
[Vue Router warn]: No match found for location with path "/_tailwind/config.json"
[Vue Router warn]: No match found for location with path "/_tailwind/config.json"
[Vue Router warn]: No match found for location with path "/_tailwind/js/app.eb7ca967.js.map"
[Vue Router warn]: No match found for location with path "/_tailwind/js/app.eb7ca967.js.map"
[Vue Router warn]: No match found for location with path "/_tailwind/js/app.eb7ca967.js.map"
[Vue Router warn]: No match found for location with path "/_tailwind/js/app.eb7ca967.js.map"
[Vue Router warn]: No match found for location with path "/_tailwind/favicon.ico"
[Vue Router warn]: No match found for location with path "/_tailwind/favicon.ico"
[Vue Router warn]: No match found for location with path "/_tailwind/favicon.ico"
[Vue Router warn]: No match found for location with path "/_tailwind/favicon.ico"`

**Comment by maxdzin** [comment] 2022-04-23 09:27
Same for me on the fresh Nuxt v3.0.0-rc1 app.
```No match found for location with path...``` and the errors in console.

**Comment by aresgun** [comment] 2022-04-23 11:55
There is a problem in here, the viewer isn't working with Nuxt v3.0.0-rc1

**Comment by Butch78** [comment] 2022-04-26 16:19
I'm getting the same errors.. 

<img width="591" alt="image" src="https://user-images.githubusercontent.com/19205392/165346369-6cea3f0e-2caa-4592-8671-6490f459d8e6.png">

If you run tailwind viewer with this command:

```npx tailwind-config-viewer```

It will work but It will take over the http://localhost:3000 port

**Comment by gstamosbg** [comment] 2022-05-01 16:14
Same error here, on fresh install.

![image](https://user-images.githubusercontent.com/6755277/166154661-9fe675be-fed0-4e2e-8215-26658e07e410.png)

**Comment by jiblett1000** [comment] 2022-05-01 18:01
Same here

**Comment by aacassandra** [comment] 2022-05-03 17:42
Same here, can't open /_tailwind

/_tailwind/...css 404 not found
maybe config.json not found

sometime only show github logo, 
somtime only show toggle switch for darkmode
sometime white screen

**Comment by gluktd** [comment] 2022-05-10 05:41
Any updates on this?

**Comment by jiblett1000** [comment] 2022-05-10 06:33
There's a pull request for it

**Comment by StanleyMasinde** [comment] 2022-05-10 07:42
> There's a pull request for it

Could you please link it here?

**Comment by StanleyMasinde** [comment] 2022-05-10 07:44
NVM i've seen it #460

**Comment by fabis94** [comment] 2022-05-17 08:27
Great that there's a fix for this :) Any estimates for when this will be merged?

**Comment by lustremedia** [comment] 2022-06-03 13:48
I just tried to install tailwind with nuxt3 but the viewer did not work and out of the box no config was loaded etc. So it does not seem to work with nuxt3 without manual installation. The documentation is also still showing videos with nuxt2 ...

**Comment by DesKevinMendez** [comment] 2022-06-03 15:32
Issue has been fixed here [issue](https://github.com/rogden/tailwind-config-viewer/pull/58/files) Just we wait for merge it and then, redownload files

**Comment by DesKevinMendez** [comment] 2022-06-03 15:39
Issue has been fixed with the versión 1.7.1 for [tailwind-config-viewer](https://github.com/rogden/tailwind-config-viewer)

It has been merged and publish 3 days ago.
https://github.com/rogden/tailwind-config-viewer/pull/58#issuecomment-1142127655

We need open a new PR for nuxt with the new version package.

If you need to know what version of tailwind-config-view you have, you must run the next command.

`yarn list | grep tailwind-config-viewer` in my case: I have 1.7.0

**Closed** 2022-07-07 14:36 UTC
Labels: bug

**Comment by canhkieu** [comment] 2022-08-27 03:32
404 again on http://localhost:3000/_tailwind/
```json
"nuxt": "3.0.0-rc.8",
"@nuxtjs/tailwindcss": "^5.3.2",
```

![image](https://user-images.githubusercontent.com/136077/187012784-5af86386-7d7e-4275-8e4b-16ad5fab9a67.png)

**Comment by lnfel** [comment] 2022-09-03 07:29
Same here.
```json
"nuxt": "3.0.0-rc.8",
"@nuxtjs/tailwindcss": "^5.3.2",
"tailwindcss": "^3.1.8"
```

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/47680867/188260282-b9fd8274-db53-4827-948f-b900629f1fe7.png">

I was able to make this work with this config.

```js
// nuxt.config.ts
export default defineNuxtConfig({
    css: ['~/assets/css/tailwind.css'],
    build: {
        postcss: {
            postcssOptions: {
                plugins: {
                    tailwindcss: {},
                    autoprefixer: {},
                },
            },
        },
    },
    modules: [
        '@nuxtjs/tailwindcss'
    ]
})
```
And in my `app.vue`
```html
<script lang="ts" setup>
    import './assets/css/tailwind.css'
</script>
```

But my extended color is not being read by tailwind viewer:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/47680867/188260612-98055642-8c44-4bac-b9c8-db6f5f307462.png">

At this point I can ditch out `@nuxtjs/tailwindcss` and have minimal config in `nuxt.config.ts`:
```js
export default defineNuxtConfig({
    build: {
        postcss: {
            postcssOptions: {
                plugins: {
                    tailwindcss: {},
                    autoprefixer: {},
                },
            },
        },
    },
})
```
While still keeping the `import './assets/css/tailwind.css'` in `app.vue`.

**Comment by broose-goose** [comment] 2022-10-15 17:35
Looks like a version bump broke it. 1.7.2 fails, but 1.71 works. per @DesKevinMendez

`$ npm install --save-dev tailwind-config-viewer@1.7.1`

**Comment by fernandolangaro** [comment] 2022-11-01 22:05
Same here, I'm getting this warns when tryinto to access [http:localhost:3000/_tailwind](url)

This path works, and displays all tailwind viewer data, but the warn is annoying.

<img width="848" alt="Captura de Tela 2022-11-01 às 19 02 57" src="https://user-images.githubusercontent.com/66561216/199350765-38f8f41c-610b-41ba-a8c6-d9a074635248.png">

**Comment by andreidmour** [comment] 2023-08-29 09:19
This problem persists in the latest version of nuxt 3 and tailwind module. Please open this again.

**Comment by ineshbose** [comment] 2023-08-29 10:38
> This problem persists in the latest version of nuxt 3 and tailwind module. Please open this again.

Do you have `ssr: false`? If yes, it could be #651, and if no, could you provide a reproduction please?

**Comment by rob-kristie-mach** [comment] 2023-08-31 18:14
I have same issue with fresh install.  Just shows a blank page, no viewer

`Nuxt 3.7.0 with Nitro 2.6.2                                                                                                           10:57:54 AM
                                                                                                                                      10:57:54 AM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                                                 nuxt:tailwindcss 10:57:54 AM
✔ Nuxt DevTools is enabled v0.8.2 (experimental)                                                                                     10:57:55 AM
ℹ Tailwind Viewer: http://localhost:3000/_tailwind/                                                                 nuxt:tailwindcss 10:57:55 AM

 WARN  [@vue/compiler-sfc] defineProps is a compiler macro and no longer needs to be imported.                                        10:57:55 AM



 WARN                                                                                                                                 10:57:56 AM


[10:57:56 AM]  WARN  warn - No utility classes were detected in your source files. If this is unexpected, double-check the content option in your Tailwind CSS configuration.


 WARN  warn - https://tailwindcss.com/docs/content-configuration                                                                      10:57:56 AM

ℹ Vite client warmed up in 611ms                                                                                                     10:57:56 AM
✔ Nitro built in 291 ms                                                                                                        nitro 10:57:56 AM
ℹ Restarting nuxt...                                                                                                                 10:58:33 AM
ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                                                 nuxt:tailwindcss 10:58:33 AM
✔ Nuxt DevTools is enabled v0.8.2 (experimental)                                                                                     10:58:33 AM
ℹ Tailwind Viewer: http://localhost:3000/_tailwind/                                                                 nuxt:tailwindcss 10:58:33 AM
ℹ Vite client warmed up in 395ms                                                                                                     10:58:34 AM
✔ Nitro built in 216 ms                                                                                                        nitro 10:58:34 AM
[Vue Router warn]: No match found for location with path "/_tailwind"
[Vue Router warn]: No match found for location with path "/_tailwind"
[Vue Router warn]: No match found for location with path "/css/app.aac7915f.css"
[Vue Router warn]: No match found for location with path "/css/app.aac7915f.css"
[Vue Router warn]: No match found for location with path "/js/app.487587de.js"
[Vue Router warn]: No match found for location with path "/js/app.487587de.js"
[Vue Router warn]: No match found for location with path "/js/chunk-vendors.d4b2e20c.js"
[Vue Router warn]: No match found for location with path "/js/chunk-vendors.d4b2e20c.js"
[Vue Router warn]: No match found for location with path "/_tailwind"
[Vue Router warn]: No match found for location with path "/_tailwind"
[Vue Router warn]: No match found for location with path "/css/app.aac7915f.css"
[Vue Router warn]: No match found for location with path "/css/app.aac7915f.css"
[Vue Router warn]: No match found for location with path "/js/app.487587de.js"
[Vue Router warn]: No match found for location with path "/js/app.487587de.js"
[Vue Router warn]: No match found for location with path "/js/chunk-vendors.d4b2e20c.js"
[Vue Router warn]: No match found for location with path "/js/chunk-vendors.d4b2e20c.js"
[Vue Router warn]: No match found for location with path "/_tailwind"
[Vue Router warn]: No match found for location with path "/_tailwind"
[Vue Router warn]: No match found for location with path "/_tailwind"
[Vue Router warn]: No match found for location with path "/_tailwind"`

**Comment by fabis94** [comment] 2023-08-31 18:46
@rob-kristie-mach Did you actually open `/_tailwind` or `/_tailwind/`? There's been a weird bug for a while where if you don't add that trailing slash, it's just gonna show a blank page

**Comment by pepongucte266** [comment] 2023-10-16 13:55
I'm facing the same issue
`"@nuxtjs/tailwindcss": "^6.8.0",`

**Comment by blowsie** [comment] 2023-10-26 08:54
Same issue with latest packages
```json
  "dependencies": {
    "@pinia/nuxt": "^0.5.1",
    "@vueuse/nuxt": "^10.5.0"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.2",
    "nuxt": "^3.8.0",
    "vue": "^3.3.6",
    "vue-router": "^4.2.5"
  }
  ```

**Comment by lustremedia** [comment] 2023-10-26 23:46
> Same issue with latest packages
> 
> ```json
>   "dependencies": {
>     "@pinia/nuxt": "^0.5.1",
>     "@vueuse/nuxt": "^10.5.0"
>   },
>   "devDependencies": {
>     "@nuxt/devtools": "latest",
>     "@nuxtjs/tailwindcss": "^6.8.0",
>     "@pinia-plugin-persistedstate/nuxt": "^1.1.2",
>     "nuxt": "^3.8.0",
>     "vue": "^3.3.6",
>     "vue-router": "^4.2.5"
>   }
> ```

  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/color-mode": "^3.3.0",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.2",
    "@pinia/nuxt": "^0.5.1",
    "nuxt": "^3.8.0",
    "sass": "^1.69.4",
    "vue": "^3.3.6",
    "vue-router": "^4.2.5"
  }

I have the same setup and it is working for me .... ¯\_(ツ)_/¯ what is your OS?

**Comment by wJoenn** [comment] 2023-11-03 21:22
Same issue on a fresh install

![image](https://github.com/nuxt-modules/tailwindcss/assets/75388869/2ea35888-b306-4e1a-b1ff-7259b1bb62ad)
```json
  "devDependencies": {
    "@nuxt/devtools": "^1.0.0",
    "@nuxtjs/tailwindcss": "^6.9.4",
    "nuxt": "^3.8.0",
    "vue": "^3.3.7",
    "vue-router": "^4.2.5"
  }
```

The viewer works fine when launched from `http://localhost:3000/_tailwind/` but it won't work in the devtool itself
@Atinux could it be an issue with the devtool ?

Btw I'm using WSL in case that changes anything

**Comment by ineshbose** [comment] 2023-11-03 21:54
> Same issue on a fresh install
> 
> ![image](https://github.com/nuxt-modules/tailwindcss/assets/75388869/2ea35888-b306-4e1a-b1ff-7259b1bb62ad)
> ```json
>   "devDependencies": {
>     "@nuxt/devtools": "^1.0.0",
>     "@nuxtjs/tailwindcss": "^6.9.4",
>     "nuxt": "^3.8.0",
>     "vue": "^3.3.7",
>     "vue-router": "^4.2.5"
>   }
> ```
> 
> The viewer works fine when launched from `http://localhost:3000/_tailwind/` but it won't work in the devtool itself
>  could it be an issue with the devtool ?
> 
> I created a reproduction on stackblitz to make sure it wasn't coming from WSL or my setup
> https://stackblitz.com/edit/nuxt-starter-jwoekj?file=nuxt.config.ts

You navigated to /modules/_tailwind. Please go to /_tailwind and it should work.

**Comment by ineshbose** [comment] 2023-11-03 21:55
Can I please get a confirmation if this is only happening in `ssr: false`? (thumbs up or down)

**Comment by wJoenn** [comment] 2023-11-03 22:49
@ineshbose I don't get to choose what I navigate to within the devtool.
I just click on the tailwind viewer button and that's what I'm redirected to.
Feel free to have a look at the stackblitz I shared and tell me if you see anything I've done wrong in `nuxt.config.ts`

**Comment by dhait** [comment] 2023-11-05 19:03
@fabis94 Solution above worked for me -- you NEED the trailing slash.   This was on a fresh install.

**Comment by ineshbose** [comment] 2023-11-05 19:10
I'm able to see the issues with the viewer..
1. You need a trailing slash, but it shouldn't be (we put the redirect in the middleware)
2. When you do have the trailing slash, `tailwind-config-viewer` gets 404 while fetching `/_tailwind/config.json`
3. (I'm still investigating what happens in `ssr: false`)

Please lets continue discussing this issue in #561
