### ISSUE TITLE
Custom utility: @apply can only be used for classes in the same CSS tree.

### ISSUE THREAD

**Issue by phamhongphuc** [nuxt-community/tailwindcss-module#140] opened 2020-08-09 17:51 UTC
### Version
`@nuxtjs/tailwindcss: v3.0.0`
`nuxt: 2.14.1`

### Reproduction Link
https://codesandbox.io/s/tailwindcss-issue-1jf8w

### Steps to reproduce

Document: https://tailwindcss.com/docs/adding-new-utilities

In `tailwind.pcss`, I create a custom class like:
```pcss
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';

@responsive {
  .global-class { 
    @apply text-blue-400
  }
}
```

The `.global-class` or `sm:global-class` can be use in `<template>`.
But it can't be use in `<style lang="postcss">` with `@apply`

```vue
<style lang="postcss">
.component-class {
  @apply text-blue-400; /* work */
}
.apply-component-class {
  @apply component-class; /* work */
}
.apply-global-class {
  @apply global-class; /* doesn't work, throw build error */
}
</style>
```
### What is Expected?

`@apply global-class;` will be work

### What is actually happening?

`@apply global-class;` throw build error

`@apply` can only be used for classes in the same CSS tree.

```log
Module build failed (from ./node_modules/postcss-loader/src/index.js): SyntaxError (26:3) `@apply` cannot be used with `.global-class` because `.global-class` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.global-class` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```

![image](https://user-images.githubusercontent.com/11532116/89738487-2c8a3180-daa3-11ea-9635-dd1f0ecc5305.png)

**Comment by nomadboy20** [comment] 2020-09-02 22:08
same issue cant fix it

**Comment by peoray** [comment] 2020-09-07 14:39
Anyway to fix this? I'm also having the same issue

**Comment by hacknug** [comment] 2020-09-09 14:57
I think this is a duplicate of #123.

This is happening because Nuxt treats style tags on SFC's as a different CSS file/block and they only have whatever comes from PostCSS as context. If you want this to work, you'll probably need to write a Tailwind plugin to add those base styles, components or utilities. After your styles come from a plugin, everything should work as you expect.

I'm just guessing here but I would almost bet this is the case.

**Comment by Atinux** [comment] 2020-09-14 15:30
Hi there,

It is a weird situation indeed, I am not experimented in PostCSS sorry. Is it possible to create a working reproduction using only Vue + Tailwind? This will help me narrow the issue :)

**Comment by hacknug** [comment] 2020-09-15 18:30
> ### Reproduction Link
> 
> https://codesandbox.io/s/tailwindcss-issue-1jf8w

@Atinux does the link from OP work for you? It has a custom class on `tailwind.pcss` and he later tries to use `@apply` on `/pages/index.vue`.

**Comment by Atinux** [comment] 2020-09-24 17:10
@phamhongphuc reproduction **is valid**.

My question was to have the similar reproduction with vue-cli + ssr + tailwindcss to see if this error comes from Nuxt itself or Vue.

I found a temporary workaround by creating a `components.pcss` file and import it where you actually need it: https://codesandbox.io/s/tailwindcss-issue-forked-wwbcs?file=/pages/index.vue:416-452

**Comment by phamhongphuc** [comment] 2020-10-16 03:26
> @phamhongphuc reproduction **is valid**.
> 
> My question was to have the similar reproduction with vue-cli + ssr + tailwindcss to see if this error comes from Nuxt itself or Vue.
> 
> I found a temporary workaround by creating a `components.pcss` file and import it where you actually need it: https://codesandbox.io/s/tailwindcss-issue-forked-wwbcs?file=/pages/index.vue:416-452

I'm sorry, I don't have experience with vue-cli + ssr + tailwindcss. 
Your temporary workaround looks good but I think It isn't exactly what we need.

After weeks, I found a another way to fix this issue by creating new utilities via JS.
https://codesandbox.io/s/tailwindcss-issue-forked-nxr0w?file=/assets/tailwind.config.js

**- Pros:**
  + No build error
  + Access tailwind theme value easier.

**- Cons:**
  + No hot reload (only full reload again when force save `tailwind.config.js` or `nuxt.config.js`).
  + `yarn nuxt` process will be terminated with incomplete code in `tailwind.config.js` file (have to manual restart).

**Comment by itpropro** [comment] 2020-10-17 00:09
I use @apply with nuxtjs for a long time now and it works fine. I recently enabled the experimental complex classes feature by setting it in the tailwind.config.sj:
```Javascript
module.exports = {
  experimental: {
    applyComplexClasses: true,
...
```
I had a similar problem, but I still had imports like
```CSS
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```
in my style section and the tailwindcss file in my assets folder.
I removed the whole assets folder, as I was not doing anything with the tailwind.css and the requirement for one was dropped and I have the following tailwindcss config:
```
tailwindcss: {
    configPath: '@/tailwind.config.js',
    cssPath: '@/assets/css/tailwind.css',
    exposeConfig: false
  }
```
where all the 3 keys are only there, because I change them regularly for testing, not because they are needed.
With a clean installation and "applyComplexClasses" set to true, there should be no problem in having @apply statements like these:
```HTML
<style scoped>
.btn-base {
  @apply px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white transition ease-in-out duration-150;
}
.btn-neutral {
  @apply bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 disabled:cursor-not-allowed disabled:bg-indigo-400;
}
...
```
I hope this helps anyone.

**Closed** 2021-01-14 17:01 UTC
Labels: bug

**Comment by michaelpumo** [comment] 2021-03-01 14:17
For what it's worth, I am getting this same issue:

```
"nuxt": "^2.15.2",
"@nuxtjs/tailwindcss": "^3.4.2"
```

**Utility**:

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  @variants {
    .form-input {
      color: red;
    }
  }
}
```

...and using it like so:

```
<style lang="postcss" scoped>
.FormInput {
  @apply .form-input;
}
</style>
```

Results in an error:

> `@apply` cannot be used with `.form-input` because `.form-input` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.form-input` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

**Comment by wongwithhisfellowpartners** [comment] 2021-03-18 07:22
> Closing, please re-open if this is still relevant.

restart vscode works!

**Comment by chojnicki** [comment] 2021-03-25 03:53
> For what it's worth, I am getting this same issue:
> 
> ```
> "nuxt": "^2.15.2",
> "@nuxtjs/tailwindcss": "^3.4.2"
> ```
> 
> **Utility**:
> 
> ```
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> 
> @layer utilities {
>   @variants responsive {
>     .form-input {
>       color: red;
>     }
>   }
> }
> ```
> 
> ...and using it like so:
> 
> ```
> <style lang="postcss" scoped>
> .FormInput {
>   @apply .form-input;
> }
> </style>
> ```
> 
> Results in an error:
> 
> > `@apply` cannot be used with `.form-input` because `.form-input` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.form-input` exists, make sure that any `@import` statements are being properly processed _before_ Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

I doubt you still facing this problem after a month, but in your case it should be `@apply form-input` and not `@apply .form-input`

**Comment by michaelpumo** [comment] 2021-05-17 14:49
If anyone is getting an error in Vue SFC's PostCSS blocks with custom utilities not 'existing', hopefully this will help:

**This did NOT work** (as a rule in a CSS file):

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  .container {
    width: 100%;
    max-width: 1500px;
  }
}
```

**This DOES work** (created as a plugin inside `tailwind.config.js`):

```
const plugin = require('tailwindcss/plugin')
const pxToRem = (px, base = 16) => `${px / base}rem`

module.exports = {
  purge: [
    './components/**/*.{vue,js}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
  ],
  plugins: [
    plugin(function ({ addUtilities, theme }) {
      const customUtilities = {
        '.container': {
          width: '100%',
          maxWidth: '1500px',
        },
      }
      addUtilities(customUtilities)
    }),
  ],
}
```

Now I can do this in the SFC CSS (notice, you do not put a dot next to the custom class):

```
<style lang="postcss" scoped>
.Header {
  @apply container;
}
</style>
```

I hope this helps someone who is struggling to add custom utility classes to a Vue.js or Nuxt.js project.

**Comment by Sergey-Voskresenskiy** [comment] 2021-05-19 15:03
> I hope this helps someone who is struggling to add custom utility classes to a Vue.js or Nuxt.js project.

Your hopes were justified, thank you for the solution!

**Comment by jayarjo** [comment] 2021-07-05 17:17
@michaelpumo this solution is no fun. Can anyone confirm that original approach will NEVER work, e.g.:

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  .container {
    width: 100%;
    max-width: 1500px;
  }
}
```

?

**Comment by jods4** [comment] 2021-08-03 11:58
The `@layer` approach seems to work for me with Vite + Tailwind JIT in DEV mode.
When building for production, it isn't found though and I had to resort to the plugin approach :(

**Comment by chojnicki** [comment] 2021-08-04 00:21
> The `@layer` approach seems to work for me with Vite + Tailwind JIT in DEV mode.
> When building for production, it isn't found though and I had to resort to the plugin approach :(

Same env but I never got it to work, even with @layer. Only way is to import main css into component <style> which is not a solution, so I'm also stuck with plugin approach.
Could you maybe provide some reproduction with dev working and build not?

**Comment by pfumagalli** [comment] 2021-09-02 19:38
FWIW, I only managed to get this to work with the hint by @michaelpumo [above](https://github.com/nuxt-community/tailwindcss-module/issues/140#issuecomment-842388067) but expanded it a bit further as I prefer to have my utility classes written themselves in a `.css` file.

So, I added a little plugin to `tailwind.config.js` as follows:

```js
const plugin = require('tailwindcss/plugin')
const fs = require('fs')

module.exports = {
  // ... purge, theme, variants, ...
  plugins: [
    plugin(function({ addUtilities, postcss }) {
      const css = fs.readFileSync('./tailwind.utilities.postcss', 'utf-8')
      addUtilities(postcss.parse(css).nodes)
    }),
  ],
}
```

My `tailwind.utilities.postcss` goes along the lines of:

```css
.my-headline-1 {
  @apply tracking-tight;
  @apply text-3xl sm:text-4xl md:text-5xl xl:text-6xl;
  @apply mb-4 md:mb-5 lg:mb-6;
}

/* ... all other utilities */
```

Then in my `.vue` files, in the `<style lang="postcss" scoped>` I can always `@apply my-headline-1;` no problem!

Only downside is that changes to `tailwind.utilities.postcss` don't automatically appear in development until I start and stop my dev server, but I can't figure out whether that's something related to Vite caching things a bit too thoroughly or some Tailwind code not overriding classes when `addUtilities(...)` is called several times with the same class names.

Better than nothing :-)

I hope this helps!

**Comment by okaysk** [comment] 2021-09-17 06:34
in tailwind.config.js, you need to put the **mode: 'jit'**.

like
`module.exports = {
    mode: 'jit',
    purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {},
    },
    variants: {
        extend: {},
    },
    plugins: [],
}
`

**Comment by ztxone** [comment] 2021-10-03 10:27
> in tailwind.config.js, you need to put the **mode: 'jit'**.

This works! Thank you! VIte+Vue3+Tailwindcss build

**Comment by ejirocodes** [comment] 2021-10-06 11:40
Works in Vue 3 when I did 👇🏽 

`tailwind.config.js`
`ringColor: (theme) => ({
      DEFAULT: theme('colors.blue.500', '#2156C9'),
      ...theme('colors'),
      focus_border: '#2156C9',
    }),`



`tailwind.css`
`focus:ring-focus_border`

**Comment by subuta** [comment] 2021-12-10 03:29
Based on @pfumagalli 's comment at https://github.com/nuxt-community/tailwindcss-module/issues/140#issuecomment-911997165, I added few more improvements. With this workaround, I can use my custom `c-button` component as `@apply c-button` at Vue SFC's style tag ✨ 

> So, I added a little plugin to `tailwind.config.js` as follows:

First, I had to `objectify()` PostCSS nodes. thus I added `postcss-js` . that is included as dependency of tailwindcss package already. or should manually added by `npm i postcss-js -D`

```js
// tailwind.config.js
const plugin = require('tailwindcss/plugin')
const postcssJs = require('postcss-js')
const fs = require('fs')

module.exports = {
  // ... purge, theme, variants, ...
  plugins: [
    plugin(function({ addComponents, postcss }) {
      const css = fs.readFileSync('./assets/css/components.pcss', 'utf-8')
      addComponents(postcssJs.objectify(postcss.parse(css)))
    }),
  ],
}
```

> Only downside is that changes to tailwind.utilities.postcss don't automatically appear in development until I start and stop my dev server

For fix this issue, I added `watch` options to `nuxt.config.js`. then Nuxt's dev server will automatically restarted on component style changes! Needs manual reload of the browser for apply new changes still (not working well with HMR), but more convenient than manual restart.

```js
// nuxt.config.js
export default {
  // ... other nuxt options ....
  watch: [
    '@/assets/css/components.pcss',
  ]
}
```

This is my `assets/css/components.pcss` for demonstration. No need to wrap styles by `@layer` with this workaround.

```postcss
/* Contents inside this file are automatically treated as "@layer components" */
.c-button {
  @apply py-2 px-4 bg-theme-red font-bold text-white rounded;
}
```

---

Confrimed on following package versions.

- nuxt@2.15.8
- @nuxtjs/tailwindcss@4.2.1
- tailwindcss@2.2.19
    - postcss-js@3.0.3

**Comment by daviddarx** [comment] 2022-06-29 05:39
The second step of the solution above doesn't work for me, with nuxt3 and vite default config. 
The first steps work and I don't get any error when applying custom classes in the SFC, but I still need to restart nuxt to get the changes made on the custom class visible. 

Any solution for this config? 
"nuxt": "3.0.0-rc.4"
"@nuxtjs/tailwindcss": "^5.1.3",

many thanks!

**Comment by BenMaldoner** [comment] 2023-04-26 17:49
for us it worked to directly use "tailwindcss" (3.3.2) according to https://tailwindcss.com/docs/guides/nuxtjs instead of "@nuxtjs/tailwindcss" (^3.4.3).
