### ISSUE TITLE
tailwindcss@2.1.3 will cause every single file in the project to be watched

### ISSUE THREAD

**Issue by foxted** [nuxt-community/tailwindcss-module#359] opened 2021-06-13 00:03 UTC
### Version
@nuxtjs/tailwindcss: 4.1.3
nuxt: 2.15.6
tailwind: >=2.1.3

### Reproduction Link
No reproduction link but here's the tailwindcss PR that causes the problem: https://github.com/tailwindlabs/tailwindcss/pull/4530

### Steps to reproduce

Install a new project with @nuxtjs/tailwindcss and tailwindcss@2.1.3 or higher.

### What is Expected?

Only the relevant project files are being watched and trigger a nuxt rebuild. 

### What is actually happening?

Any file in the project, including node modules, markdown files, github workflows, IDE specific files, anything is being watched and trigger a nuxt rebuild.

---

I think it comes from the new behaviour brought by this PR: https://github.com/tailwindlabs/tailwindcss/pull/4530

This PR added  a new "glob check" on paths provided to purge CSS. If the path is a glob, it will watch the directory instead. 

Which is fine for these paths: 

```
`${srcDir}/components/**/*.{vue,js,ts}`,
`${srcDir}/layouts/**/*.vue`,
`${srcDir}/pages/**/*.vue`,
`${srcDir}/plugins/**/*.{js,ts}`,
```

But this one is causing the issue: 

```
`${rootDir}/nuxt.config.{js,ts}`
```

Tailwind will now consider this a glob and thus push the entire `rootDir` to be watched.

A potential quick fix for this would be to explicitly watch Javascript and Typescript config separately, to avoid tailwind thinking it must watch the whole directory: 

```
`${rootDir}/nuxt.config.js`,
`${rootDir}/nuxt.config.ts`
```

**Comment by AlexanderBelokon** [comment] 2021-06-24 14:58
I've created a minimal reproduction repo for this issue: https://github.com/AlexanderBelokon/nuxt-tailwind-watch
It only manifests itself when [Tailwind's JIT](https://github.com/tailwindlabs/tailwindcss/tree/master/src/jit) is active and breaks git running on windows on WSL1.

**Comment by medairbit** [comment] 2021-06-24 17:20
This issue also causes Webpack to constantly builds/rebuilds storybook.

**Comment by foxted** [comment] 2021-06-24 18:03
@AlexanderBelokon It happened for me without Tailwind JIT active

**Comment by AlexanderBelokon** [comment] 2021-06-24 19:34
@foxed That's interesting, in my repro I can't trigger this behavior without JIT, and I didn't find an override for purge that would do it. The paths in the original post have variables that are not defined, so I could not get them to (not) work as expected.

Could you please provide an example config that does?

**Comment by foxted** [comment] 2021-06-24 21:15
The default paths are the following: 

```
purge: {
    content: [
      `${srcDir}/components/**/*.{vue,js,ts}`,
      `${srcDir}/layouts/**/*.vue`,
      `${srcDir}/pages/**/*.vue`,
      `${srcDir}/plugins/**/*.{js,ts}`,
      `${rootDir}/nuxt.config.{js,ts}`
    ]
  }
```

Defined in https://github.com/nuxt-community/tailwindcss-module/blob/main/src/tailwind.config.ts

In my project's tailwind config, I have the following: 



```
purge: {
        content: [
            'components/**/*.vue',
            'layouts/**/*.vue',
            'pages/**/*.vue',
            'templates/**/*.vue',
            'plugins/**/*.js',
            'nuxt.config.js'
        ]
    }
```

The problem comes from the use of `{js,ts}` on the nuxt config path, which results in watching `{$rootDir}`.

**Comment by AlexanderBelokon** [comment] 2021-06-25 12:02
Added this to my repro: https://github.com/AlexanderBelokon/nuxt-tailwind-watch/commit/2dfeb654ea344b4195a51e6022ad1b393d84b9a7, it does not trigger the problem on my machine without JIT, probably something else from your config is needed too.

**Comment by foxted** [comment] 2021-06-25 22:38
Up to tailwind@2.1.2 it was working fine though 🤔

**Comment by creazy231** [comment] 2021-07-06 11:56
any quickfix for this issue?

**Comment by fabis94** [comment] 2021-07-06 12:16
@creazy231 I did this in my nuxt.config.js:

![image](https://user-images.githubusercontent.com/938316/124598235-12043800-de6d-11eb-97b6-cb098101cce9.png)

**Comment by creazy231** [comment] 2021-07-06 12:19
thanks, that should do it till there is a fix for this issue 👍

**Comment by Atinux** [comment] 2021-07-06 16:07
Could you please try https://github.com/nuxt-community/tailwindcss-module/releases/tag/v4.2.1 and confirm it's good?

**Closed** 2021-07-06 16:06 UTC
Labels: bug

**Comment by fabis94** [comment] 2021-07-06 16:19
@Atinux seems to work for me, thank you!

**Comment by creazy231** [comment] 2021-07-06 16:35
> Could you please try https://github.com/nuxt-community/tailwindcss-module/releases/tag/v4.2.1 and confirm it's good?

works for me 👍

**Comment by AlexanderBelokon** [comment] 2021-07-06 18:07
@Atinux works for me too, thanks a lot! 🎉

**Comment by Benjamin-Lee** [comment] 2022-03-08 05:19
I reproduced this in 5.0.0-4 and the fix @fabis94 posted worked for me.

**Comment by 93lucasp** [comment] 2022-04-07 13:27
The problem is not fixed for me `"nuxt": "^2.15.8"`

**Comment by 93lucasp** [comment] 2022-04-07 13:32
> @creazy231 I did this in my nuxt.config.js:
> 
> ![image](https://user-images.githubusercontent.com/938316/124598235-12043800-de6d-11eb-97b6-cb098101cce9.png)

**Comment by pachiraDIG** [comment] 2022-04-07 23:47
@93lucasp Just experienced the same issue with those versions, also with the above solutions not working. At the moment, I'm able to temporarily fix by removing `'@nuxtjs/eslint-module'` from `buildModules`

**Comment by 93lucasp** [comment] 2022-04-08 04:27
@pachiraDIG yes removing `'@nuxtjs/eslint-module'` fixed the problem, thanks a lot.

But eslint now will continue to work? 🤔

**Comment by slavanossar** [comment] 2022-04-08 05:25
This is still happening with `@nuxtjs/tailwindcss@5.0.2`, HMR is running when `.eslintcache` updates, and also when there are changes within the `.git` directory.

**Comment by 93lucasp** [comment] 2022-04-08 05:28
yes but you can fix it as @pachiraDIG seggested.

@Atinux could you give a look to this problem please? :)

**Comment by slavanossar** [comment] 2022-04-08 05:35
Yep just wanted to add another report so the regression can get fixed.

For posterity (and so it can be easily copied), this is what needs to be added to `nuxt.config.js`

```js
  watchers: {
    // Temporary fix: https://github.com/nuxt-community/tailwindcss-module/issues/359
    webpack: {
      ignored: [
        '**/*.eslintcache',
        '**/.git/**'
      ]
    }
  }
```

**Comment by 93lucasp** [comment] 2022-04-08 05:39
@slavanossar yes it is working also this solution, thanks a lot for sharing :)
