### ISSUE TITLE
Activating jit breaks font face import

### ISSUE THREAD

**Issue by Paalt** [nuxt-community/tailwindcss-module#299] opened 2021-03-16 16:40 UTC
### Version
@nuxtjs/tailwindcss: 4.0.1
nuxt: 2.15.3

### Steps to reproduce
in nuxt.config.js:
`
tailwindcss: {
  jit: true,
},
`

in assets/css/tailwind.css
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
	@font-face {
		font-family: 'Archivo Black';
		font-weight: 400;
		src: url('~assets/fonts/ArchivoBlack-Regular.ttf') format('truetype');
	}
}
```

### What is Expected?
That the font is loaded correctly

### What is actually happening?
When running npm run dev , I get this error:

in ./assets/css/tailwind.css                                                                                                                                                
friendly-errors 17:31:18

Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js):                                                                                       friendly-errors 17:31:18
Error: Can't resolve '___CSS_LOADER_URL_REPLACEMENT_0___' in '/Users/paltaulebrentebraten/Development/Professional/wright-admin/assets/css'
    at /Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
    at /Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
    at /Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/paltaulebrentebraten/Development/Professional/wright-admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
                                                                                                                                                                                    friendly-errors 17:31:18
 @ ./assets/css/tailwind.css 4:14-221 15:3-20:5 16:22-229
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js

Setting jit to false resolves the problem. Figured this is something to do with the nuxt module and not related to tailwind/jit

**Comment by mattatcubix** [comment] 2021-03-17 01:26
The issue is with JIT and has been fixed in the latest version. See https://github.com/tailwindlabs/tailwindcss-jit/issues/23

**Closed** 2021-06-16 23:09 UTC
Labels: bug, wontfix
