### ISSUE TITLE
Overriding Tailwind CSS @apply Directives in a NuxtJS App

### ISSUE THREAD

**Issue by thecodeclimber** [nuxt-community/tailwindcss-module#127] opened 2020-06-23 07:45 UTC
I am trying to create a custom VueJS components using TailwindCSS and NuxtJS.  At times, I want to use the tailwind css `@apply` directive to style my component.  Something like this:

```html
<template>
 <div class="card">
   ...
 </div>
</template>

<style>
 .card {
   @apply bg-grey-200 text-grey-800;
  }
</style>
```

I then want the capability of **overriding** those styles when I use the component.  Something like this:

```html
<Card class="bg-blue-200">...</Card>
```

Now, this is technically possible -- it just requires organizing the tailing base css file in the right way.  Namely, like this:

```css
@tailwind base;
@tailwind components;
.card {
  @apply bg-grey-200 text-grey-800;
}
@tailwind utilities;
```

That is to say, `@tailwind utilities` needs to come **after** the custom class names.  The problem is that with `nuxt` it seems to be the opposite -- namely, the custom class names (and their css styles) come **after** the tailwind utilities.  

How can I change this in NuxtJS?

For what it is worth, I am using the `@nuxtjs/tailwindcss` module with default installation:  

```js
  buildModules: [
    // Doc: https://github.com/nuxt-community/nuxt-tailwindcss
    '@nuxtjs/tailwindcss',
  ],
```

**Comment by Atinux** [comment] 2020-08-04 23:20
Cam you please provide a codesandbox with what you want to demonstrate?

**Comment by azrikahar** [comment] 2020-08-25 14:03
> That is to say, @tailwind utilities needs to come after the custom class names. The problem is that with nuxt it seems to be the opposite -- namely, the custom class names (and their css styles) come after the tailwind utilities.

@thecodeclimber I may be wrong here, but I think it's not necessarily a Nuxt problem, but more of a Vue problem with the CSS in Single File Components being loaded last. Declaring the styles **before** the `@tailwind utilities` line does work as you mentioned (and in the Tailwind docs), but we will then be unable to keep the CSS inside (and even scoped) each SFCs and keep things organized.

---

With that said, I believe the solution for your use case is [the `important` option](https://tailwindcss.com/docs/configuration#important) in your `tailwind.config.js` file, especially when we're talking about overriding CSS styles.

Here is how we can toggle this option in the `tailwind.config.js` file:

```js
module.exports = {
  ...
  important: true,
  ...
}
```

and here is an example of what your Card component will look like:

```vue
<template>
  <div class="card">
    ...
  </div>
</template>

<style scoped>
.card {
  @apply p-4 rounded border;
}
.card-gray {
  @apply bg-gray-200 text-gray-800 border-gray-300;
}
.card-blue {
  @apply bg-blue-200 text-blue-800 border-blue-300;
}
</style>
```

I added `.card-gray` & `.card-blue` as examples with `.card` being the base class. I do recommend going through the [Keeping things composable](https://tailwindcss.com/docs/extracting-components#keeping-things-composable) section in the Tailwind docs to understand more on the reasoning of such structure.

Then in your `pages/index.vue` page, the following template:

```vue
<template>
  <div class="p-4 space-y-4">
    <Card>Base Card</Card>
    <Card class="card-gray">Gray Card</Card>
    <Card class="card-blue">Blue Card</Card>
    <Card class="text-green-800 bg-green-200 border-green-300"
      >Custom Green Card</Card
    >
    <Card class="card-blue text-red-800 bg-red-200 border-red-300"
      >Override from Blue to Red Card</Card
    >
  </div>
</template>
```

will produce the following output:

![chrome_X8xXLsDVfH](https://user-images.githubusercontent.com/42867097/91183077-9bab8b00-e71d-11ea-9abe-b37ce96dd53a.png)

For clearer demonstration purpose, I added the classes of each card as an array in bold text. **The one that should interest you the most would be the last red card, where the `.card-blue` class already applied blue background and text like your example, but the `text-red-800 bg-red-200 border-red-300` classses still ends up overriding it like you wanted.**

Here is the codesandbox link for you to check it out easily: https://codesandbox.io/s/modest-sound-sib1u

**Comment by hacknug** [comment] 2020-09-09 15:22
> With that said, I believe the solution for your use case is [the `important` option](https://tailwindcss.com/docs/configuration#important) in your `tailwind.config.js` file, especially when we're talking about overriding CSS styles.

Nah, this would do the trick but it's not the best way to do it since then you _might_ have to fight your own specificity wars at some point in the future.

Take a look at [the `@layer` directive](https://tailwindcss.com/docs/functions-and-directives#layer) in core. That should let you write those classes as components (I mean Tailwind components, not SFC) and they will be inserted before the utility classes so you can then override as intended.

Keep in mind there's a potential gotcha due to how Nuxt (I guess) processes those CSS files and blocks. I mentioned [a workaround](https://github.com/nuxt-community/tailwindcss-module/issues/140#issuecomment-689618395) in #140 that should work in case that happens.

**Comment by Atinux** [comment] 2020-09-14 15:32
I think we need to resolve #140 in order to solve this one too.

**Closed** 2021-01-14 17:05 UTC
Labels: pending, question
